### PR TITLE
Integration test

### PR DESCRIPTION
**Pull request by braincee**
**In this pull request, these are the project requirements:**

-  Fixed all the N+1 problems encountered when fetching all posts and their comments for a user.
- Set up Capybara to write integration tests for all views in the project.

  - **_User index page:_**
   - I can see the username of all other users.
   - I can see the profile picture for each user.
   - I can see the number of posts each user has written.
   - When I click on a user, I am redirected to that user's show page.

  - **_User show page:_**
  - I can see the user's profile picture.
  - I can see the user's username.
  - I can see the number of posts the user has written.
  - I can see the user's bio.
  - I can see the user's first 3 posts.
  - I can see a button that lets me view all of a user's posts.
  - When I click a user's post, it redirects me to that post's show page.
  - When I click to see all posts, it redirects me to the user's post's index page.
  
  - **_User post index page:_**
  - I can see the user's profile picture.
  - I can see the user's username.
  - I can see the number of posts the user has written.
  - I can see a post's title.
  - I can see some of the post's body.
  - I can see the first comments on a post.
  - I can see how many comments a post has.
  - I can see how many likes a post has.
  - I can see a section for pagination if there are more posts than fit on the view.
  - When I click on a post, it redirects me to that post's show page.
  
  - **_Post show page:_**
  - I can see the post's title.
  - I can see who wrote the post.
  - I can see how many comments it has.
  - I can see how many likes it has.
  - I can see the post body.
  - I can see the username of each commenter.
  - I can see the comment each commenter left.

_**To test for capybara integrational test**_

 - To install rspec: gem install rspec
 - To test: rspec
 - To test specific folder: rspec spec/integration
 - To test specific file: rspec spec/integration/filename_spec.rb

### CODE REVIEW

**Review by m05e5 — CHANGES_REQUESTED** [review]
Hi @braincee , 

Good job so far. !
There are some issues that you still need to work on to go to the next project but you are almost there!
mario_ladders


## Highlights


## Required Changes ♻️
* You really did a great job but there are some features you need to improve

- [ ] Please check the comments below 
- [ ] Due to an issue in your spec/models, the testing throws an error. This is because in your test files you called for the `Author` model but in your project, there is no author model
image

After commenting out all the other testing files except the integration, it falls out that not all you test cases are ok
image

_I'm sure you can do it just keep it up_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_@m05e5_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by braincee** [comment]
The project requirement was Integration Testing using Capybara

 - This is a screenshot of a test for `user index`

**User index page:**

- I can see the username of all other users.

- I can see the profile picture for each user.

- I can see the number of posts each user has written.

- When I click on a user, I am redirected to that user's show page.

**To test  this file : rspec spec/integration/user_index_spec.rb**

Screenshot (33)


This is a screenshot of a test for `user show`:

**User show page:**

- I can see the user's profile picture.

- I can see the user's username.

- I can see the number of posts the user has written.

- I can see the user's bio.

- I can see the user's first 3 posts.

- I can see a button that lets me view all of a user's posts.

- When I click a user's post, it redirects me to that post's show page.

- When I click to see all posts, it redirects me to the user's post's index page.

**To test this file : rspec spec/integration/user_show_spec.rb**

Screenshot (34)

This is a screenshot for the test `post index`:

**User post index page:**

- I can see the user's profile picture.

- I can see the user's username.

- I can see the number of posts the user has written.

- I can see a post's title.

- I can see some of the post's body.

- I can see the first comments on a post.

- I can see how many comments a post has.

- I can see how many likes a post has.

- I can see a section for pagination if there are more posts than fit on the view.

- When I click on a post, it redirects me to that post's show page.

**To test this file: rspec spec/integration/posts_index_spec.rb**

Screenshot (35)


This is a screenshot for the test `post show`

**User post show page **

Post show page:

- I can see the post's title.

- I can see who wrote the post.

- I can see how many comments it has.

- I can see how many likes it has.

- I can see the post body.

- I can see the username of each commenter.

- I can see the comment each commenter left.

**To test for this file: rspec spec/integration/posts_show_spec.rb**




Screenshot (36)

**Review by Davidosky007 — APPROVED** [review]
Hi @braincee @AACHOURMOHAMED 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* No linter errors 👍 
* All tests passed ✔️ 
* Proper use of Gitflow 👍 
* Good looking readme file 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by braincee** [comment]
Thanks very much, @m05e5, @Davidosky007 and @AACHOURMOHAMED 

thankyou-thankyou-tantan

**Pull request merged**
